//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrevyBurgess.Games.TrevyChess.ChessGameUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrevyBurgess.Games.TrevyChess.ChessGameUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap B_Bishop {
            get {
                object obj = ResourceManager.GetObject("B_Bishop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap B_King {
            get {
                object obj = ResourceManager.GetObject("B_King", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap B_Knight {
            get {
                object obj = ResourceManager.GetObject("B_Knight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap B_Pawn {
            get {
                object obj = ResourceManager.GetObject("B_Pawn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap B_Queen {
            get {
                object obj = ResourceManager.GetObject("B_Queen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap B_Rook {
            get {
                object obj = ResourceManager.GetObject("B_Rook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help_16x16 {
            get {
                object obj = ResourceManager.GetObject("Help_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trevy Chess is Super Cool.
        /// </summary>
        internal static string Help_DialogBoxMessage {
            get {
                return ResourceManager.GetString("Help_DialogBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chess.
        /// </summary>
        internal static string Menu_Chess {
            get {
                return ResourceManager.GetString("Menu_Chess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        internal static string Menu_Chess_Difficulty {
            get {
                return ResourceManager.GetString("Menu_Chess_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string Menu_Chess_Difficulty_1 {
            get {
                return ResourceManager.GetString("Menu_Chess_Difficulty_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Menu_Chess_Difficulty_2 {
            get {
                return ResourceManager.GetString("Menu_Chess_Difficulty_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string Menu_Chess_Difficulty_3 {
            get {
                return ResourceManager.GetString("Menu_Chess_Difficulty_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        internal static string Menu_Chess_Difficulty_4 {
            get {
                return ResourceManager.GetString("Menu_Chess_Difficulty_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Master.
        /// </summary>
        internal static string Menu_Chess_Difficulty_5 {
            get {
                return ResourceManager.GetString("Menu_Chess_Difficulty_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Against Computer.
        /// </summary>
        internal static string Menu_Chess_PlayAgainstComputer {
            get {
                return ResourceManager.GetString("Menu_Chess_PlayAgainstComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player&apos;s Color.
        /// </summary>
        internal static string Menu_Chess_PlayerColor {
            get {
                return ResourceManager.GetString("Menu_Chess_PlayerColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string Menu_Chess_PlayerColor_Black {
            get {
                return ResourceManager.GetString("Menu_Chess_PlayerColor_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string Menu_Chess_PlayerColor_White {
            get {
                return ResourceManager.GetString("Menu_Chess_PlayerColor_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string Menu_File_New {
            get {
                return ResourceManager.GetString("Menu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Menu_File_Print {
            get {
                return ResourceManager.GetString("Menu_File_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Tpoics.
        /// </summary>
        internal static string Menu_Help_HelpTopics {
            get {
                return ResourceManager.GetString("Menu_Help_HelpTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string Menu_HomeTab_GameGroup_Name {
            get {
                return ResourceManager.GetString("Menu_HomeTab_GameGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Menu_HomeTab_Name {
            get {
                return ResourceManager.GetString("Menu_HomeTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play without Rules.
        /// </summary>
        internal static string Menu_Tools_PlayWithoutRules {
            get {
                return ResourceManager.GetString("Menu_Tools_PlayWithoutRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Chess Codes.
        /// </summary>
        internal static string Menu_Tools_ShowChessCodes {
            get {
                return ResourceManager.GetString("Menu_Tools_ShowChessCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Board.
        /// </summary>
        internal static string Menu_View_RotateBoard {
            get {
                return ResourceManager.GetString("Menu_View_RotateBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Messages.
        /// </summary>
        internal static string Menu_View_ShowSillyMessages {
            get {
                return ResourceManager.GetString("Menu_View_ShowSillyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Bar.
        /// </summary>
        internal static string Menu_View_StatusBar {
            get {
                return ResourceManager.GetString("Menu_View_StatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Bar.
        /// </summary>
        internal static string Menu_View_ToolBar {
            get {
                return ResourceManager.GetString("Menu_View_ToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap New_16x16 {
            get {
                object obj = ResourceManager.GetObject("New_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select piece to replace pawn.
        /// </summary>
        internal static string PawnPromotion_Instructions {
            get {
                return ResourceManager.GetString("PawnPromotion_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Piece {
            get {
                object obj = ResourceManager.GetObject("Piece", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Printer_16x16 {
            get {
                object obj = ResourceManager.GetObject("Printer_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Printer_48x48 {
            get {
                object obj = ResourceManager.GetObject("Printer_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedoMoveImage {
            get {
                object obj = ResourceManager.GetObject("RedoMoveImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Square1 {
            get {
                object obj = ResourceManager.GetObject("Square1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Square2 {
            get {
                object obj = ResourceManager.GetObject("Square2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player&apos;s Color: Black.
        /// </summary>
        internal static string Status_PlayersColor_Black {
            get {
                return ResourceManager.GetString("Status_PlayersColor_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player&apos;s Color: White.
        /// </summary>
        internal static string Status_PlayersColor_White {
            get {
                return ResourceManager.GetString("Status_PlayersColor_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player&apos;s Turn: Black.
        /// </summary>
        internal static string Status_PlayersTurn_Black {
            get {
                return ResourceManager.GetString("Status_PlayersTurn_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player&apos;s Turn: White.
        /// </summary>
        internal static string Status_PlayersTurn_White {
            get {
                return ResourceManager.GetString("Status_PlayersTurn_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Level:.
        /// </summary>
        internal static string Toolbar_Difficulty {
            get {
                return ResourceManager.GetString("Toolbar_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Level: Easy.
        /// </summary>
        internal static string Toolbar_Difficulty_1 {
            get {
                return ResourceManager.GetString("Toolbar_Difficulty_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        internal static string Toolbar_Difficulty_1_Color {
            get {
                return ResourceManager.GetString("Toolbar_Difficulty_1_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Level: Medium.
        /// </summary>
        internal static string Toolbar_Difficulty_2 {
            get {
                return ResourceManager.GetString("Toolbar_Difficulty_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string Toolbar_Difficulty_2_Color {
            get {
                return ResourceManager.GetString("Toolbar_Difficulty_2_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Level: Hard.
        /// </summary>
        internal static string Toolbar_Difficulty_3 {
            get {
                return ResourceManager.GetString("Toolbar_Difficulty_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreenYellow.
        /// </summary>
        internal static string Toolbar_Difficulty_3_Color {
            get {
                return ResourceManager.GetString("Toolbar_Difficulty_3_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Level: Expert.
        /// </summary>
        internal static string Toolbar_Difficulty_4 {
            get {
                return ResourceManager.GetString("Toolbar_Difficulty_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        internal static string Toolbar_Difficulty_4_Color {
            get {
                return ResourceManager.GetString("Toolbar_Difficulty_4_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Level: Grand Master.
        /// </summary>
        internal static string Toolbar_Difficulty_5 {
            get {
                return ResourceManager.GetString("Toolbar_Difficulty_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plum.
        /// </summary>
        internal static string Toolbar_Difficulty_5_Color {
            get {
                return ResourceManager.GetString("Toolbar_Difficulty_5_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Against Computer.
        /// </summary>
        internal static string Toolbar_PlayAgainstComputer {
            get {
                return ResourceManager.GetString("Toolbar_PlayAgainstComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Against Player.
        /// </summary>
        internal static string Toolbar_PlayAgainstPlayer {
            get {
                return ResourceManager.GetString("Toolbar_PlayAgainstPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Board.
        /// </summary>
        internal static string Toolbar_RotateBoard {
            get {
                return ResourceManager.GetString("Toolbar_RotateBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Color.
        /// </summary>
        internal static string Toolbar_UserColor {
            get {
                return ResourceManager.GetString("Toolbar_UserColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TrevyChess {
            get {
                object obj = ResourceManager.GetObject("TrevyChess", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trevy Chess.
        /// </summary>
        internal static string TrevyChessTitle {
            get {
                return ResourceManager.GetString("TrevyChessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UndoMoveImage {
            get {
                object obj = ResourceManager.GetObject("UndoMoveImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap W_Bishop {
            get {
                object obj = ResourceManager.GetObject("W_Bishop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap W_King {
            get {
                object obj = ResourceManager.GetObject("W_King", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap W_Knight {
            get {
                object obj = ResourceManager.GetObject("W_Knight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap W_Pawn {
            get {
                object obj = ResourceManager.GetObject("W_Pawn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap W_Queen {
            get {
                object obj = ResourceManager.GetObject("W_Queen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap W_Rook {
            get {
                object obj = ResourceManager.GetObject("W_Rook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
